import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "./layouts/Header";
import Footer from "./layouts/Footer";
import './fontawsome'; // import file fontawesome.ts
// import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Rikkei Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}
        <Header></Header>
        trang chủ
        <Footer></Footer>
      </body>
    </html>
  );
}
